# Generated by Django 3.0.9 on 2021-05-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
