# Generated by Django 3.0.9 on 2021-05-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolExchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
