# Generated by Django 3.0.9 on 2021-05-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolExchange', '0003_auto_20210503_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='title',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
