# Generated by Django 3.0.9 on 2021-05-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolExchange', '0004_auto_20210503_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
