# Generated by Django 3.0.9 on 2021-05-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolExchange', '0006_auto_20210503_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
